target_machine:
  - x86_64
centos_machine:
  - x86_64
cross_target_platform:
  - linux-64
sysroot_cdt_arch:
  - x86_64

ctng_vendor:
  - conda
sysroot_cdt_name:
  - conda_2_28

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine
    - sysroot_cdt_arch
